" enter the current millenium
set nocompatible

" Clean up ~/
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim

" Formatting
set smartindent
set autoindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
syntax on

" Visual cues
set number

" Theme
set t_Co=256
colorscheme nighted

" Misc
let &titlestring = "Vim " . expand("%:t") . " @ " . hostname()
set title
let &iconstring = "vim"
set icon

" Gamer Fix
nnoremap G gg
nnoremap gg G
